### ISSUE TITLE
Increase texture aesthetics

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/Neroxis-Map-Generator#195]
This reorders the textures and adds additional smoothing to reduce blockiness

**Comment by Penguin5** [comment]
Substantially changed how all texture layers/masks are used/calculated/determined/placed (slopes are much better represented, mountains/hills/ramps/etc are much more precise, textures are generally smoothed/blended a lot more, and more texture layers are now used sufficiently and generally with much greater levels of detail and more aesthetic qualities)
