### ISSUE TITLE
Native compilation

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/Neroxis-Map-Generator#2]
The python client needs a native executable without a JRE.

**Comment by Geosearchef** [comment]
Investigating Excelsior JET.

**Comment by muellni** [comment]
I'm investigating a native C++ port using libeigen.

**Comment by Geosearchef** [comment]
Why though? That will just make the implementation harder to understand, harder to work on and I don't think it will yield any noticable performamce boost.

I'm also closing this issue as it is a leftover from times when the py client didn't have a JRE (which it has due to ICE now)
