### ISSUE TITLE
user reports map being placed in wrong folder

### ISSUE THREAD

**Issue by phongu** [FAForever/Neroxis-Map-Generator#270]
LordMichael reports that he has to manually move maps from 
C:\Program Files (x86)\Steam\steamapps\common\Supreme Commander Forged Alliance\maps
to
C:\Users\<user>\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance\maps
after generation

**Comment by Sheikah45** [comment]
hmm that is pretty odd. Is he using the faf client to generate the maps?

**Comment by phongu** [comment]
he was joining my game

**Comment by Sheikah45** [comment]
Likely this was the case of him unknowingly using the fallback location. Which is also removed in the next client version, or also having a manually edited client.prefs
