### ISSUE TITLE
1.8.6 Biomes

### ISSUE THREAD

**Issue by ghost** [FAForever/Neroxis-Map-Generator#307]
--biomes command is missing

![image](https://user-images.githubusercontent.com/86099479/188307269-2f6b40d6-5ffc-4e72-954a-8acd2ab13b99.png)

**Comment by ghost** [comment]
1.8.5

![image](https://user-images.githubusercontent.com/86099479/188307483-04de0bce-7090-49d4-94c7-062effcfec01.png)

**Comment by ghost** [comment]
Is this depreciated functionality?

**Comment by Sheikah45** [comment]
Added back
