### ISSUE TITLE
(Reported?) Map size in-game differs from requested size

### ISSUE THREAD

**Issue by DZychlinski** [FAForever/Neroxis-Map-Generator#309]
I ran map generator 1.8.7.jar with the following command:
java -jar -Xmx8G NeroxisGen_1.8.7.jar --style=LOW_MEX --map-size=60km --spawn-count=12

Even though requested size was 60km, SC reports this map as being 81km in game lobby:
![obraz](https://user-images.githubusercontent.com/2663626/190418918-c2fb5547-1ba9-4efa-8f5d-bb671fb72dd3.png)

I don't quite know how to verify which is true, I'd suppose generator did as requested, but messed some map size info for the game itself.
All is fine for maps of 40km size, but as I recall, 50km and 55km were also reported as being 81km.

This is output from that run:
neroxis_map_generator_1.8.7_pyrzcscuphbk6_bqyaeca
Starting pipeline
Pipeline completed!
Map generation done: 594478 ms
File export done: 6848 ms
Saving map to D:\Games\Supreme Commander Forged Alliance\Map generator\.\neroxis_map_generator_1.8.7_pyrzcscuphbk6_bqyaeca
Seed: 9089268212804731567
Spawns: 12
Map Size: 3072
Num Teams: 2
Biome: WindingRiver
Land Density: 0.17872763
Plateau Density: 0.35782045
Mountain Density: 0.26176775
Ramp Density: 0.5786311
Reclaim Density: 0.67216694
Mex Density: 0.037175983
Terrain Symmetry: POINT4
Symmetry Settings: SymmetrySettings(terrainSymmetry=POINT4, teamSymmetry=POINT2, spawnSymmetry=POINT4)
Style: LOW_MEX
TerrainGenerator: BasicTerrainGenerator
TextureGenerator: BasicTextureGenerator
ResourceGenerator: LowMexResourceGenerator
PropGenerator: BasicPropGenerator
DecalGenerator: BasicDecalGenerator

**Comment by Sheikah45** [comment]
This is more an artifact of the game. Map binary files have to be a power of 2. So the map file is 81km. However to make a 60km map we restrict the play area of the map to 60km so when you play the map is the size requested. 

For the lobby to display the actual size w would have to change the lobby code to read the map size from the playable area and not the file size. So ultimately this is not a generator issue.
