### ISSUE TITLE
Shadow calculation produces wrong results

### ISSUE THREAD

**Issue by BlackYps** [FAForever/Neroxis-Map-Generator#350]
The shadow calculation for the shadow decal is not working correctly. It is most evident on biomes with a low sun, e.g. loki. The shadowed areas are basically the areas that the game already shadows because they are facing away from the sun, but there should be some long stretched shadows instead.
The copyAsShadowMask function seems to try a basic raytracing, but I don't really understand what is happening there, so I am a bit lost, but I am pretty sure that the culprit is there.

**Comment by BlackYps** [comment]
Partly false alarm, it was a configuration issue with the map shader. The shadow map does have blocky artifacts though, so it would be nice to get rid of them.

**Comment by BlackYps** [comment]
Here is an example of the shadow map. Notice the blocky edges
![grafik](https://user-images.githubusercontent.com/52536103/236808441-513afcf5-e8fa-475a-b6c6-d2bfcf172e7f.png)

**Comment by Sheikah45** [comment]
Blocky edges are because of the resolution, only higher resolution can resolve those

**Comment by BlackYps** [comment]
It turned out that the blocky edges are compression artifacts that go away when saving the texture without compression.
But now that we are able to have nice shadows I noticed that the shadow length is incorrect. It's noticeable when you teleport a unit to a cliff edge like here.
![Screenshot 2023-05-09 111325](https://github.com/FAForever/Neroxis-Map-Generator/assets/52536103/26928e85-125b-4dac-ac01-6e70e5bdd27c)
The cliffs have a consistent height, so the shadow should basically follow the cliff edge as a parallel line.
![Screenshot 2023-05-09 111400](https://github.com/FAForever/Neroxis-Map-Generator/assets/52536103/0bf4ae9b-d6a5-41b3-bf02-2ef7c70a316c)

The shadows are not always too short, sometimes they are too long as well.
![Screenshot 2023-05-09 111456a](https://github.com/FAForever/Neroxis-Map-Generator/assets/52536103/86d835cc-601d-4da8-839a-4a1fe1b477e5)

**Comment by Sheikah45** [comment]
Do you know how the game calculates unit shadows?

**Comment by BlackYps** [comment]
It uses pretty standard shadow mapping. The actual shadow map calculation happens in the engine, so it's not accessible

**Comment by Sheikah45** [comment]
The map generator uses standard ray casting so need to know how the algorithm differs to implement a matching one.

**Comment by Sheikah45** [comment]
The examples you posted more so look like there is a 90 degree difference between the assumed light angles in the xz plane

**Comment by BlackYps** [comment]
The xz plane is which one?

**Comment by Sheikah45** [comment]
The one parallel to the ground

**Comment by BlackYps** [comment]
Maybe. I am pretty sure that there is a bug somewhere in your implementation. My brain can't make sense of the shadows the way they are now. Maybe some testing with some cleaner sun angles and geometry reveals the problem

**Comment by Sheikah45** [comment]
All it does right now is traverse the angle from the lighting direction and if the point is lower than the projected light point it marks it as shadow.

So basically follows the line of shadow from a point. It is all discretized so that may have some effect. But if you test and come back with something that would be helpful to debug as otherwise it is a fairly simple implementation.

**Comment by Sheikah45** [comment]
Was an issue in the new-shader branch with modifying the heightmap before creating the shadow
