### ISSUE TITLE
Graphics bug with the water ramp on the `PRAYER` biome

### ISSUE THREAD

**Issue by Garanas** [FAForever/Neroxis-Map-Generator#389]
**Describe the bug**

The water ramp is applied disproportionally on a generated map using the `PRAYER` biome:

![image](https://github.com/FAForever/fa/assets/15778155/86345d08-e9d8-4680-a3b0-08f4b0cbeb4c)

**To Reproduce**

Generate a map using the `PRAYER` biome and spawn in an amphibious unit. Move the unit under water, see the black-ness being applied disproportionally.

**Expected behavior**

Similar water ramp effect as on other maps.

**Comment by BlackYps** [comment]
This is a bug with the map generator. The standard biomes should not have a light multiplier of 2.2 as this triggers the code for exponential water absorption in units. I think this is a leftover from the original idea to enhance the existing biomes. Instead we are creating new biomes now.
