### ISSUE TITLE
Add History to Visual Debugger

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/Neroxis-Map-Generator#56]
Remove need for Debugger to remove concurrency and display only the most recent version of the mask.
Add history to Visual Debugger GUI.

**Comment by Katharsas** [comment]
Nice, didnt think about using stracktrace xD

**Comment by Sheikah45** [comment]
Yeah it works pretty well the only issue is inflate is reported as deflate but not too big a deal

**Comment by Katharsas** [comment]
I mean you could just pass  string to the update calls from the operations^^
